import {it,expect} from 'vitest';
import fs from 'node:fs';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
const source=fs.readFileSync('public/app.js','utf8');
function helper(secciones,excepciones=[],allowedTabs=[]){const a=source.indexOf('const INICIO_ACCESOS_TITULO'),b=source.indexOf('async function renderInicio(',a);if(a<0)throw Error('Falta el bloque de accesos');const c={seccionesVisiblesParaRol:()=>secciones,excepcionesDelRol:()=>excepciones,state:{allowedTabs},SECTION_DEFS:{obra:{label:'Obra'}},esc:s=>String(s).replaceAll('<','&lt;'),tabIcon:t=>'<svg></svg>',TAB_LABELS:{avance:'Avance',ordenesCambio:'Órdenes de cambio'}};vm.createContext(c);vm.runInContext(source.slice(a,b),c);return vm.runInContext('accesosInicioHtml()',c);}
it('un solo módulo genera solo su sección y un botón accesible',()=>{const h=helper([{id:'obra',def:{label:'Obra'},tabs:['avance']}]);expect(h.match(/data-inicio-tab=/g)).toHaveLength(1);expect(h).toContain('data-inicio-tab="avance"');expect(h).toContain('<h4 id="inicioAccesos-obra">Obra</h4>');expect(h).not.toMatch(/style=|\$/);});
it('sin módulos muestra el mensaje explícito y ningún botón muerto',()=>{const h=helper([]);expect(h).toContain('Todavía no tienes módulos asignados en esta obra. Pide acceso al administrador.');expect(h).not.toContain('<button');});
it('incluye la excepción suelta del sidebar solo cuando está permitida',()=>{const ex=[{tab:'ordenesCambio',seccionOrigen:'obra'}];expect(helper([],ex,['ordenesCambio'])).toContain('data-inicio-tab="ordenesCambio"');expect(helper([],ex,[])).not.toContain('<button');});
it('no muta el modelo de navegación al incorporar excepciones',()=>{const sec=[{id:'obra',def:{label:'Obra'},tabs:['avance']}];helper(sec,[{tab:'ordenesCambio',seccionOrigen:'obra'}],['ordenesCambio']);expect(sec[0].tabs).toEqual(['avance']);});
function permisos(src){const c={};vm.createContext(c);const constants=src.slice(src.indexOf('const MAQUINARIA_TABS_ADMIN'),src.indexOf('\nconst ROLE_TABS') );const role=src.slice(src.indexOf('const ROLE_TABS'),src.indexOf('\n};',src.indexOf('const ROLE_TABS'))+3);const mapStart=src.indexOf('const TAB_A_SECCION =');const map=src.slice(mapStart,src.indexOf('\n};',mapStart)+3);const fnStart=src.indexOf('function defaultPermisosParaRolFrontend');const fn=src.slice(fnStart,src.indexOf('\nfunction ',fnStart+10));vm.runInContext(constants+role+map+fn,c);return JSON.parse(JSON.stringify(vm.runInContext("defaultPermisosParaRolFrontend('residente')",c)));}
it('la alineación visual no amplía el preset del editor de permisos',()=>{const original=execFileSync('git',['show','origin/main:public/app.js'],{encoding:'utf8',maxBuffer:4e6});expect(permisos(source)).toEqual(permisos(original));});
