import {beforeAll,afterAll,it,expect} from 'vitest';import request from 'supertest';import app from '../server/app.js';import db from '../server/db.js';import contexto from './inicio-residente-contexto.cjs';import {execFileSync} from 'node:child_process';import Module from 'node:module';import path from 'node:path';
let c;const filename=path.resolve('server/inicio-baseline-virtual.cjs'),baselineModule=new Module(filename);baselineModule.filename=filename;baselineModule.paths=Module._nodeModulePaths(path.dirname(filename));baselineModule._compile(execFileSync('git',['show','origin/main:server/app.js'],{encoding:'utf8',maxBuffer:4*1024*1024}),filename);const baseline=baselineModule.exports;
beforeAll(async()=>{c=await contexto.crear()},90000);afterAll(async()=>{try{await contexto.limpiar(c)}finally{await db.pool.end()}},90000);
const nav=async(u,target=process.env.QA_NAV_BASELINE==='1'?baseline:app)=>{const r=await request(target).get('/api/projects/'+c.pid+'/nav-tabs').set(contexto.A(u.token));expect(r.status).toBe(200);console.log('NAV '+u.perfil+':',JSON.stringify(r.body.tabs));return r.body.tabs};
it('residente sin permisos → ninguna tab',async()=>{expect(await nav(c.ninguno)).toEqual([]);const r=await request(app).get('/api/projects/'+c.pid+'/ordenes').set(contexto.A(c.ninguno.token));console.log('ABRIR NINGUNO ordenes:',r.status);expect(r.status).toBe(403)});
it('residente solo avance → únicamente avance',async()=>{expect(await nav(c.solo)).toEqual(['avance']);expect((await request(app).get('/api/projects/'+c.pid+'/avances').set(contexto.A(c.solo.token))).status).toBe(200);expect((await request(app).get('/api/projects/'+c.pid+'/ordenes').set(contexto.A(c.solo.token))).status).toBe(403)});
it.each(['admin','dev'])('%s conserva nav-tabs idéntico a origin/main',async(perfil)=>{const original=await nav(c[perfil],baseline),actual=await nav(c[perfil]);console.log('DIFF '+perfil+':',JSON.stringify({eliminadas:original.filter(t=>!actual.includes(t)),agregadas:actual.filter(t=>!original.includes(t))}));expect(actual).toEqual(original)});
it('todos los módulos del residente típico tienen lectura HTTP200',async()=>{const endpoints={programa:'/programa',avance:'/avances',destajo:'/destajistas',requisiciones:'/requisiciones',insumos:'/insumos',nominas:'/nominas',trabajadores:'/trabajadores',estimaciones:'/estimaciones',generadoresObra:'/generadores-obra',ordenesCambio:'/ordenes-cambio',lotes:'/lotes',modelosVivienda:'/modelos-vivienda',matrices:'/matrices',generadorPresupuestos:'/matrices',ordenes:'/ordenes',almacen:'/almacen/salidas',maquinaria_catalogo:'/api/maquinaria/equipos',maquinaria_horas:'/api/maquinaria/horas',maquinaria_consumibles:'/api/maquinaria/consumibles',maquinaria_reportes_cliente:'/api/maquinaria/reporte-clientes'};for(const tab of await nav(c.tipico)){expect(endpoints[tab],tab).toBeTruthy();const endpoint=endpoints[tab].startsWith('/api/')?endpoints[tab]:'/api/projects/'+c.pid+endpoints[tab],r=await request(app).get(endpoint).set(contexto.A(c.tipico.token));console.log('ABRIR TIPICO:',tab,endpoint,r.status);expect(r.status,tab+' '+JSON.stringify(r.body)).toBe(200)}});

it('permisos globales de Proveedores/Cumplimiento prevalecen sobre un grant por obra',async()=>{
 const u=c.compras,permisos=[{seccion:'proveedores',puede_ver:false,puede_crear:false,puede_editar:false}];
 expect((await request(app).put('/api/permisos/'+u.id).set(contexto.A(c.adminToken)).send({proyecto_id:null,permisos})).status).toBe(200);
 expect((await request(app).put('/api/permisos/'+u.id).set(contexto.A(c.adminToken)).send({proyecto_id:c.pid,permisos:[{...permisos[0],puede_ver:true}]})).status).toBe(200);
 const old=await nav(u,baseline),actual=await nav(u);console.log('GLOBAL vs OBRA:',JSON.stringify({origin:old,actual}));expect(old).toContain('proveedores');expect(old).toContain('cumplimiento');expect(actual).not.toContain('proveedores');expect(actual).not.toContain('cumplimiento');
 for(const tab of ['proveedores','cumplimiento']){const r=await request(app).get('/api/'+tab).set(contexto.A(u.token));console.log('ABRIR GLOBAL sin permiso:',tab,r.status);expect(r.status).toBe(403)}
});
